"use client"

import type React from "react"

import { useEffect, useState } from "react"

/**
 * Renders its children only on the client-side after hydration.
 * Useful for components that cause hydration mismatches due to client-specific logic
 * or dynamic IDs generated by libraries like Radix UI.
 */
export function ClientOnly({ children }: { children: React.ReactNode }) {
  const [hasMounted, setHasMounted] = useState(false)

  useEffect(() => {
    setHasMounted(true)
  }, [])

  if (!hasMounted) {
    return null
  }

  return <>{children}</>
}
