export const countriesData = [
  {
    slug: "china-visa",
    name: "China",
    image: "/images/great-wall-china.png",
    processing: "7-10 business days (standard), 3-5 business days (express)",
    requirements: "Valid passport, visa application form, recent passport-sized photo, flight itinerary, hotel booking, bank statement, invitation letter (for business/family visit).",
    goodFor: "Tourism, business, family visits, cultural exchange.",
    visaTypes: [
      {
        type: "Tourist Visa (L Visa)",
        description: "For individuals traveling to China for tourism purposes.",
        duration: "30-90 days, single or double entry.",
        requirements: [
          "Passport valid for at least 6 months with blank pages.",
          "Completed visa application form.",
          "Recent passport-sized color photo.",
          "Round-trip flight tickets and hotel reservations.",
          "Itinerary in China.",
          "Bank statement showing sufficient funds.",
        ],
      },
      {
        type: "Business Visa (M Visa)",
        description: "For individuals traveling to China for commercial and trade activities.",
        duration: "30-180 days, single, double, or multiple entry.",
        requirements: [
          "Passport valid for at least 6 months with blank pages.",
          "Completed visa application form.",
          "Recent passport-sized color photo.",
          "Invitation letter from a Chinese company or organization.",
          "Proof of business activities (e.g., business license, trade records).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form (accurately filled)",
      "Recent Passport-sized Photo (white background)",
      "Flight Itinerary (round-trip)",
      "Hotel Booking Confirmation",
      "Bank Statement (proof of funds)",
      "Invitation Letter (if applicable)",
      "Previous Chinese Visas (if any)",
    ],
    applicationSteps: [
      { title: "Prepare Documents", description: "Gather all required documents including passport, photos, and supporting letters." },
      { title: "Fill Application Form", description: "Complete the visa application form accurately and sign it." },
      { title: "Submit Application", description: "Submit your application in person or via an authorized agency." },
      { title: "Pay Fees", description: "Pay the visa application fees at the time of submission." },
      { title: "Track Status", description: "Monitor your application status online or through the agency." },
      { title: "Collect Visa", description: "Pick up your passport with the approved visa." },
    ],
    faqs: [
      { question: "Do I need an invitation letter for a tourist visa?", answer: "Generally, for a tourist visa, an invitation letter is not strictly required if you have confirmed flight and hotel bookings. However, it can strengthen your application." },
      { question: "How long can I stay in China with a tourist visa?", answer: "A typical tourist visa (L Visa) allows a stay of 30 to 90 days per entry, depending on the specific visa issued." },
      { question: "Can I apply for a China visa online?", answer: "The application process usually requires physical submission of documents to the Chinese Embassy or Consulate, or through a visa service center. Online applications are generally not available for the full process." },
    ],
  },
  {
    slug: "tourist-thailand-visa",
    name: "Tourist Thailand",
    image: "/images/tourist-thailand-visa.png",
    processing: "5-7 business days",
    requirements: "Passport, flight itinerary, hotel booking, proof of funds.",
    goodFor: "Leisure travel, short stays.",
    visaTypes: [
      {
        type: "Tourist Visa (TR)",
        description: "For individuals traveling to Thailand for tourism.",
        duration: "60 days, single or multiple entry.",
        requirements: [
          "Passport valid for at least 6 months.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations.",
          "Proof of adequate finance (20,000 THB per person or 40,000 THB per family).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Bank Statement (proof of funds)",
    ],
    applicationSteps: [
      { title: "Gather Documents", description: "Collect all necessary documents as per visa type." },
      { title: "Complete Form", description: "Fill out the visa application form accurately." },
      { title: "Submit to Embassy/Consulate", description: "Submit your application to the Royal Thai Embassy or Consulate." },
      { title: "Pay Fee", description: "Pay the applicable visa fee." },
      { title: "Await Processing", description: "Wait for the visa to be processed." },
      { title: "Collect Passport", description: "Retrieve your passport with the visa." },
    ],
    faqs: [
      { question: "Can I extend my tourist visa in Thailand?", answer: "Yes, a tourist visa can usually be extended for an additional 30 days at an immigration office in Thailand." },
      { question: "Is a visa required for all nationalities to enter Thailand?", answer: "Many nationalities can enter Thailand visa-free for short stays (e.g., 30 days). It's best to check specific requirements for your nationality." },
    ],
  },
  {
    slug: "destination-thailand-visa",
    name: "Destination Thailand",
    image: "/images/destination_thailand.png",
    processing: "5-7 business days",
    requirements: "Passport, flight itinerary, hotel booking, proof of funds.",
    goodFor: "Leisure travel, short stays.",
    visaTypes: [
      {
        type: "Tourist Visa (TR)",
        description: "For individuals traveling to Thailand for tourism.",
        duration: "60 days, single or multiple entry.",
        requirements: [
          "Passport valid for at least 6 months.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations.",
          "Proof of adequate finance (20,000 THB per person or 40,000 THB per family).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Bank Statement (proof of funds)",
    ],
    applicationSteps: [
      { title: "Gather Documents", description: "Collect all necessary documents as per visa type." },
      { title: "Complete Form", description: "Fill out the visa application form accurately." },
      { title: "Submit to Embassy/Consulate", description: "Submit your application to the Royal Thai Embassy or Consulate." },
      { title: "Pay Fee", description: "Pay the applicable visa fee." },
      { title: "Await Processing", description: "Wait for the visa to be processed." },
      { title: "Collect Passport", description: "Retrieve your passport with the visa." },
    ],
    faqs: [
      { question: "Can I extend my tourist visa in Thailand?", answer: "Yes, a tourist visa can usually be extended for an additional 30 days at an immigration office in Thailand." },
      { question: "Is a visa required for all nationalities to enter Thailand?", answer: "Many nationalities can enter Thailand visa-free for short stays (e.g., 30 days). It's best to check specific requirements for your nationality." },
    ],
  },
  {
    slug: "italy-visa",
    name: "Italy",
    image: "/images/italy-visa.png",
    processing: "10-15 business days",
    requirements: "Passport, Schengen visa application form, flight itinerary, hotel booking, travel insurance, proof of funds.",
    goodFor: "Tourism, cultural exploration, Schengen area travel.",
    visaTypes: [
      {
        type: "Schengen Tourist Visa (Type C)",
        description: "For short stays (up to 90 days in any 180-day period) for tourism, visiting family, or business.",
        duration: "Up to 90 days.",
        requirements: [
          "Passport valid for at least 3 months beyond intended stay.",
          "Schengen visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations or proof of accommodation.",
          "Travel medical insurance (minimum coverage €30,000).",
          "Proof of sufficient funds.",
          "Letter of invitation (if applicable).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 3 months beyond stay)",
      "Schengen Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Travel Medical Insurance",
      "Bank Statement (proof of funds)",
    ],
    applicationSteps: [
      { title: "Determine Visa Type", description: "Identify the correct Schengen visa type for your travel purpose." },
      { title: "Gather Documents", description: "Collect all required documents as per the checklist." },
      { title: "Book Appointment", description: "Schedule an appointment at the Italian Embassy/Consulate or VFS Global." },
      { title: "Attend Interview & Submit", description: "Submit documents and attend the interview (if required)." },
      { title: "Pay Fees", description: "Pay the visa application fees." },
      { title: "Await Decision", description: "Wait for the visa processing to complete." },
      { title: "Collect Passport", description: "Pick up your passport with the visa." },
    ],
    faqs: [
      { question: "What is the Schengen Area?", answer: "The Schengen Area is a zone comprising 27 European countries that have abolished passport and all other types of border control at their mutual borders." },
      { question: "Can I travel to other Schengen countries with an Italian visa?", answer: "Yes, a Schengen visa issued by Italy allows you to travel freely within the entire Schengen Area for the duration of your visa." },
    ],
  },
  {
    slug: "hong-kong-visa",
    name: "Hong Kong",
    image: "/images/hong-kong-visa.png",
    processing: "5-7 business days",
    requirements: "Passport, flight itinerary, hotel booking, proof of funds.",
    goodFor: "Short visits, business, transit.",
    visaTypes: [
      {
        type: "Visitor Visa",
        description: "For tourism, social visits, or short-term business trips.",
        duration: "Up to 90 days (for most nationalities).",
        requirements: [
          "Passport valid for at least 6 months beyond intended stay.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations or proof of accommodation.",
          "Proof of sufficient funds.",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Bank Statement (proof of funds)",
    ],
    applicationSteps: [
      { title: "Check Eligibility", description: "Verify if your nationality requires a visa for Hong Kong." },
      { title: "Prepare Documents", description: "Gather all necessary documents." },
      { title: "Submit Application", description: "Submit your application to the Immigration Department of Hong Kong or a Chinese diplomatic mission." },
      { title: "Await Processing", description: "Wait for the application to be processed." },
      { title: "Receive Visa", description: "Receive your visa endorsement." },
    ],
    faqs: [
      { question: "Do I need a visa for Hong Kong if I'm transiting?", answer: "Many nationalities can transit through Hong Kong without a visa, provided they do not leave the airport transit area. Check specific rules for your nationality." },
      { question: "Can I work in Hong Kong on a visitor visa?", answer: "No, a visitor visa does not permit employment in Hong Kong. A separate work visa is required." },
    ],
  },
  {
    slug: "saudi-visa",
    name: "Saudi",
    image: "/images/saudi-visa.png",
    processing: "3-5 business days",
    requirements: "Passport, visa application form, recent photograph, invitation letter (for business/visit).",
    goodFor: "Pilgrimage (Hajj/Umrah), business, tourism.",
    visaTypes: [
      {
        type: "Tourist e-Visa",
        description: "For tourism and leisure, available to citizens of eligible countries.",
        duration: "Up to 90 days, multiple entry.",
        requirements: [
          "Passport valid for at least 6 months.",
          "Digital passport-sized photo.",
          "Accommodation details.",
          "Travel insurance.",
        ],
      },
      {
        type: "Umrah Visa",
        description: "For pilgrims performing Umrah.",
        duration: "Specific to pilgrimage period.",
        requirements: [
          "Passport valid for at least 6 months.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Proof of vaccination (Meningitis ACWY).",
          "Booking confirmation from an authorized Umrah operator.",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form (if not e-Visa)",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Invitation Letter (for business/visit visas)",
      "Proof of Vaccination (for Umrah/Hajj)",
    ],
    applicationSteps: [
      { title: "Choose Visa Type", description: "Select the appropriate visa type (e.g., e-Visa, Umrah, Business)." },
      { title: "Complete Application", description: "Fill out the online e-Visa application or traditional form." },
      { title: "Upload Documents", description: "Attach required digital documents (for e-Visa) or physical copies." },
      { title: "Pay Fees", description: "Process the visa application fee." },
      { title: "Receive Visa", description: "Receive your e-Visa via email or collect traditional visa." },
    ],
    faqs: [
      { question: "Can I perform Hajj on a tourist visa?", answer: "No, Hajj requires a specific Hajj visa. A tourist visa is not valid for Hajj pilgrimage." },
      { question: "Is travel insurance mandatory for Saudi e-Visa?", answer: "Yes, travel insurance is mandatory and is usually included in the e-Visa application fee." },
    ],
  },
  {
    slug: "korea-visa",
    name: "Korea",
    image: "/images/korea-visa.png",
    processing: "7-10 business days",
    requirements: "Passport, visa application form, recent photograph, flight itinerary, hotel booking, bank statement.",
    goodFor: "Tourism, business, cultural exchange.",
    visaTypes: [
      {
        type: "Short-Term General (C-3)",
        description: "For tourism, transit, visiting relatives, or short-term business.",
        duration: "Up to 90 days.",
        requirements: [
          "Passport valid for at least 6 months.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Flight itinerary.",
          "Hotel reservations.",
          "Bank statement (proof of funds).",
          "Invitation letter (if applicable).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Bank Statement (proof of funds)",
      "Certificate of Employment/Business Registration",
    ],
    applicationSteps: [
      { title: "Check Visa Exemption", description: "Verify if your nationality is visa-exempt for short stays." },
      { title: "Prepare Documents", description: "Gather all required documents based on your purpose of visit." },
      { title: "Fill Application Form", description: "Complete the visa application form online or manually." },
      { title: "Submit Application", description: "Submit your application to the Korean Embassy/Consulate or visa center." },
      { title: "Await Processing", description: "Wait for the visa to be processed." },
      { title: "Collect Visa", description: "Pick up your passport with the approved visa." },
    ],
    faqs: [
      { question: "Can I work in Korea with a C-3 visa?", answer: "No, the C-3 visa is for short-term visits and does not permit employment. A separate work visa is required." },
      { question: "What is K-ETA?", answer: "K-ETA (Korea Electronic Travel Authorization) is an online travel authorization required for visa-free foreign visitors entering South Korea." },
    ],
  },
  {
    slug: "schengen-visa",
    name: "Schengen",
    image: "/images/schengen.png",
    processing: "10-15 business days",
    requirements: "Passport, Schengen visa application form, flight itinerary, hotel booking, travel insurance, proof of funds.",
    goodFor: "Travel to multiple European countries, tourism, business.",
    visaTypes: [
      {
        type: "Uniform Schengen Visa (USV) - Type C",
        description: "Allows transit through or an intended stay in the territory of the Schengen Member States of a duration no more than 90 days in any 180-day period.",
        duration: "Up to 90 days.",
        requirements: [
          "Passport valid for at least 3 months beyond intended stay.",
          "Completed Schengen visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations or proof of accommodation.",
          "Travel medical insurance (minimum coverage €30,000).",
          "Proof of sufficient funds.",
          "Detailed itinerary of travel within Schengen Area.",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 3 months beyond stay)",
      "Schengen Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation",
      "Travel Medical Insurance",
      "Bank Statement (proof of funds)",
      "Letter of Employment/Study (if applicable)",
    ],
    applicationSteps: [
      { title: "Choose Main Destination", description: "Apply at the embassy/consulate of the country where you will spend most time." },
      { title: "Gather Documents", description: "Collect all required documents as per the checklist." },
      { title: "Book Appointment", description: "Schedule an appointment at the relevant embassy/consulate or visa application center." },
      { title: "Attend Interview & Submit", description: "Submit documents and attend the interview (if required)." },
      { title: "Pay Fees", description: "Pay the visa application fees." },
      { title: "Await Decision", description: "Wait for the visa processing to complete." },
      { title: "Collect Passport", description: "Pick up your passport with the visa." },
    ],
    faqs: [
      { question: "Which countries are part of the Schengen Area?", answer: "The Schengen Area includes most EU countries, plus Iceland, Liechtenstein, Norway, and Switzerland." },
      { question: "Can I apply for a Schengen visa if I have a criminal record?", answer: "A criminal record can affect your visa application. It's best to consult with the embassy or a legal expert." },
    ],
  },
  {
    slug: "japan-visa",
    name: "Japan",
    image: "/images/japan-visa.png",
    processing: "5-7 business days",
    requirements: "Passport, visa application form, recent photograph, flight itinerary, hotel booking, bank statement.",
    goodFor: "Tourism, cultural experiences, short stays.",
    visaTypes: [
      {
        type: "Temporary Visitor Visa",
        description: "For tourism, visiting relatives, or short-term business trips.",
        duration: "15, 30, or 90 days.",
        requirements: [
          "Passport valid for the period of stay.",
          "Completed visa application form.",
          "Recent passport-sized photo.",
          "Round-trip flight tickets.",
          "Hotel reservations or invitation letter from guarantor in Japan.",
          "Bank statement (proof of funds).",
          "Daily itinerary in Japan.",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for period of stay)",
      "Visa Application Form",
      "Recent Passport-sized Photo",
      "Flight Itinerary",
      "Hotel Booking Confirmation / Invitation Letter",
      "Bank Statement (proof of funds)",
      "Daily Itinerary in Japan",
    ],
    applicationSteps: [
      { title: "Check Visa Requirements", description: "Confirm if your nationality requires a visa for Japan." },
      { title: "Prepare Documents", description: "Gather all necessary documents as per the checklist." },
      { title: "Submit Application", description: "Submit your application to the Japanese Embassy/Consulate or an accredited agency." },
      { title: "Await Processing", description: "Wait for the visa processing to complete." },
      { title: "Collect Visa", description: "Pick up your passport with the approved visa." },
    ],
    faqs: [
      { question: "Can I extend my temporary visitor visa in Japan?", answer: "Extensions are generally difficult to obtain for temporary visitor visas and are granted only under exceptional circumstances." },
      { question: "Is it possible to get a multiple-entry visa for Japan?", answer: "Yes, multiple-entry visas are available for certain nationalities and under specific conditions, usually for frequent travelers." },
    ],
  },
  {
    slug: "canada-visa",
    name: "Canada",
    image: "/images/canada-visa.png",
    processing: "15-20 business days",
    requirements: "Passport, visa application form, family information, proof of funds, invitation letter (if applicable).",
    goodFor: "Tourism, visiting family, study, work.",
    visaTypes: [
      {
        type: "Visitor Visa (Temporary Resident Visa)",
        description: "For tourism, visiting family/friends, or short-term business.",
        duration: "Up to 6 months (can be extended).",
        requirements: [
          "Passport valid for at least 6 months.",
          "Completed visa application form (IMM 5257).",
          "Family Information form (IMM 5707).",
          "Recent passport-sized photos.",
          "Proof of sufficient funds.",
          "Flight itinerary (optional, but recommended).",
          "Letter of invitation (if applicable).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months)",
      "Visa Application Form (IMM 5257)",
      "Family Information Form (IMM 5707)",
      "Recent Passport-sized Photos",
      "Bank Statement (proof of funds)",
      "Letter of Invitation (if applicable)",
      "Travel Itinerary",
    ],
    applicationSteps: [
      { title: "Determine Eligibility", description: "Check if you meet the requirements for a Canadian visitor visa." },
      { title: "Gather Documents", description: "Collect all necessary documents as per the checklist." },
      { title: "Apply Online or Paper", description: "Submit your application through the IRCC online portal or by paper." },
      { title: "Pay Fees", description: "Pay the application and biometric fees." },
      { title: "Provide Biometrics", description: "Attend a biometric collection appointment." },
      { title: "Await Decision", description: "Wait for the visa processing to complete." },
      { title: "Receive Passport Request", description: "If approved, you'll receive a request to submit your passport for visa stamping." },
    ],
    faqs: [
      { question: "Can I extend my stay in Canada as a visitor?", answer: "Yes, you can apply to extend your stay as a visitor before your current status expires." },
      { question: "What is an eTA for Canada?", answer: "An Electronic Travel Authorization (eTA) is a requirement for visa-exempt foreign nationals traveling to Canada by air. It is not a visa." },
    ],
  },
  {
    slug: "usa-visa",
    name: "USA",
    image: "/images/usa-visa.png",
    processing: "Varies (interview required)",
    requirements: "Passport, DS-160 confirmation page, interview appointment confirmation, financial documents.",
    goodFor: "Tourism, business, visiting family.",
    visaTypes: [
      {
        type: "B-1 (Business Visitor)",
        description: "For temporary business trips, attending conferences, or negotiating contracts.",
        duration: "Determined by CBP at port of entry, typically up to 6 months.",
        requirements: [
          "Passport valid for at least 6 months beyond intended stay.",
          "DS-160 confirmation page.",
          "Interview appointment confirmation.",
          "Letter from employer/company.",
          "Proof of funds.",
          "Ties to home country (property, family, job).",
        ],
      },
      {
        type: "B-2 (Tourist Visitor)",
        description: "For tourism, vacation, visiting friends/relatives, or medical treatment.",
        duration: "Determined by CBP at port of entry, typically up to 6 months.",
        requirements: [
          "Passport valid for at least 6 months beyond intended stay.",
          "DS-160 confirmation page.",
          "Interview appointment confirmation.",
          "Flight itinerary (optional).",
          "Hotel reservations (optional).",
          "Proof of funds.",
          "Ties to home country (property, family, job).",
        ],
      },
    ],
    documents: [
      "Original Passport (valid for at least 6 months beyond stay)",
      "DS-160 Confirmation Page",
      "Interview Appointment Confirmation",
      "Recent Passport-sized Photo",
      "Bank Statement (proof of funds)",
      "Proof of Ties to Home Country (e.g., property deeds, marriage certificate, employment letter)",
      "Travel Itinerary (optional)",
    ],
    applicationSteps: [
      { title: "Complete DS-160 Form", description: "Fill out the online Nonimmigrant Visa Application (DS-160)." },
      { title: "Pay Visa Fee", description: "Pay the visa application fee." },
      { title: "Schedule Interview", description: "Book your visa interview appointment at a U.S. Embassy/Consulate." },
      { title: "Attend Interview", description: "Attend the interview with all required documents." },
      { title: "Await Decision", description: "Wait for the visa decision. If approved, your passport will be returned with the visa." },
    ],
    faqs: [
      { question: "How long is a B1/B2 visa valid for?", answer: "The validity period of a B1/B2 visa can vary, often from 1 to 10 years, allowing multiple entries. However, the length of stay per visit is determined by the CBP officer at the port of entry." },
      { question: "Can I change my visa status while in the U.S.?", answer: "It is possible to apply for a change of status while in the U.S., but it is generally advised to obtain the correct visa before traveling." },
    ],
  },
];
